packages:
  - playground

catalogs:
  backend:
    '@nuxt/kit': ^4.2.0
    '@nuxt/schema': ^4.2.0
  build:
    '@nuxt/module-builder': ^1.0.2
    '@types/node': ^25.0.10
    typescript: ~5.9.3
    vue-tsc: ^3.2.4
  dx:
    '@nuxt/devtools': ^3.1.1
    bumpp: ^10.1.0
  frontend:
    '@formisch/vue': ^0.6.5
    nuxt: ^4.2.0
  inlined:
    valibot: ^1.2.0
  lint:
    '@nuxt/eslint-config': ^1.13.0
    eslint: ^9.39.2
  test:
    '@nuxt/test-utils': ^4.0.0
    '@playwright/test': ^1.56.1
    '@vue/test-utils': ^2.4.6
    happy-dom: ^20.0.11
    playwright-core: ^1.56.1
    vitest: ^4.0.18
  ui:
    '@nuxt/ui': ^4.0.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi
